### ISSUE TITLE
Photo caption alignment

### ISSUE THREAD

**Issue by sylvhay** [red-list-ecosystem/typology-map-data#10]
@tmfrnz quick question re photo captions: some are left-aligned, e.g. T2.4, M1.6, while most are right-aligned. Has the alignment been changed somewhere for these - can I change them individually? or is it a bug?

![Fullscreen capture 23112020 111629 AM bmp](https://user-images.githubusercontent.com/58276776/99921485-c211ae80-2d7e-11eb-8713-b59452103984.jpg)

**Comment by tmfrnz** [comment]
@sylvhay this is indeed a small issue for captions spanning multiple lines. While currently the caption box is right-aligned, the containing text itself is not. Will fix in next update.

**Comment by tmfrnz** [comment]
moving this to https://github.com/red-list-ecosystem/typology-map/issues/43
