### ISSUE TITLE
Map issues various

### ISSUE THREAD

**Issue by tmfrnz** [red-list-ecosystem/typology-map-data#3]
@jrfep in addition to #1, here a list of other maps with problems:

- [x] [S1.2](https://global-ecosystems.org/explore/groups/S1.2): no layer specified in configuration [data/config/groups.json#L1247](https://github.com/red-list-ecosystem/typology-map-data/blob/master/data/config/groups.json#L1247)
- [x] [MFT1.1](https://global-ecosystems.org/explore/groups/MFT1.1): if river deltas should not be mapped as areas but as locations, then the layer should include points but not circular areas (that are only circular in the projection they were drawn but no longer once re-projected)
- [x] [SM1.2](https://global-ecosystems.org/explore/groups/SM1.2): no layer specified in configuration [data/config/groups.json#L1389](https://github.com/red-list-ecosystem/typology-map-data/blob/master/data/config/groups.json#L1389)

**Comment by jrfep** [comment]
[S1.2](https://global-ecosystems.org/explore/groups/S1.2) does not have a map (it is distributed everywhere, both in land and seafloor), not sure if it is better to show no map at all, or a map all in red?
Would it be possible to display an image instead of the map, like in the biome pages?

**Comment by jrfep** [comment]
Regarding [MFT1.1](https://global-ecosystems.org/explore/groups/MFT1.1): there are two or three other maps with point locality data, is there a way to add point markers for those?

**Comment by tmfrnz** [comment]
> [S1.2](https://global-ecosystems.org/explore/groups/S1.2) does not have a map (it is distributed everywhere, both in land and seafloor), not sure if it is better to show no map at all, or a map all in red?
> Would it be possible to display an image instead of the map, like in the biome pages?

Yes it would be possible to show an image, however we would probably prefer to make the map red everywhere. Ideally this would come out of a GIS layer (as this will not require any additional work, also we can use that same layer for our analysis)

**Comment by tmfrnz** [comment]
> Regarding [MFT1.1](https://global-ecosystems.org/explore/groups/MFT1.1): there are two or three other maps with point locality data, is there a way to add point markers for those?

We could indeed also add point markers however another option would be to map the true (albeit small) extent of these groups as areas and use some additional highlight layers (ie buffered areas) to enhance the data's visibility as suggested here in option 2: https://github.com/red-list-ecosystem/typology-map/issues/30

Benefits would include
- consistent representation 
- consistent handling of layers in the analysis module (calculating areas)
- small additional effort
- preparation of buffered areas for highlighting and interaction could be scripted (for round circles this would have to be done in the right projection and units of course)

This is what it might look like (we would probably go for a similar style when using map markers, however marking the circles center)
![image](https://user-images.githubusercontent.com/5811956/88048851-5a3f2300-cb54-11ea-97d8-ef152e8adcd2.png)

**Comment by jrfep** [comment]
Added a placeholder rectangle for S1.2 and copied the SM1.1 layer for SM1.2 (very similar distribution)

**Comment by jrfep** [comment]
MFT1.1 is now based on Deltas at risk layer !
